apiVersion: v1
baseDomain: prod.kafd.sa
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
  replicas: 3
metadata:
  name: scp
networking:
  clusterNetwork:
  - cidr: 172.30.0.0/16
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.47.155.0/24
  - cidr: 10.47.157.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.31.0.0/16
platform:
  vsphere:
    datacenter: Datacenter
    defaultDatastore: Datastore
    diskType: thin
    folder: /Datacenter/vm/....
    password: 
    username: 
    vCenter: 
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTA2YjMzMzQzZjAxNDA4MTlhODUyZTY1MTVlZTFkY2I6NVFJOVNTR0NWUjFFUkMyNU02Wlk0M1RaVE9QMzE1NzFVRktPNUlJVEVUS1lKMVpIS0dNMFg0RU9UTklPWk1IMQ==","email":"it.support@kafd.sa"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTA2YjMzMzQzZjAxNDA4MTlhODUyZTY1MTVlZTFkY2I6NVFJOVNTR0NWUjFFUkMyNU02Wlk0M1RaVE9QMzE1NzFVRktPNUlJVEVUS1lKMVpIS0dNMFg0RU9UTklPWk1IMQ==","email":"it.support@kafd.sa"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTQxMGRiMDEwLTcyZjEtNDBmOC04MGMwLTIyZWU5YzEyNDY3YzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBaalpsT0RBME5ESXhORGMwWm1RNFltRTROVEF5T1RVM01qQTNNRFZsWkNKOS5NWTlsejBjeW5mMW5USVluVDZJMkhqRWk0OEdJQ3BsWHhUTHlSNFlWdGFoM1diaDlIZEEwcElDRHhPNEhHY19UTjNHMzFkSXd2YVRUYlN6ZG1OSjBqaV9HWTZtXzlIZ0dvY01pREZaSTFPZnZ1QU01bnFtZDhLaWx5Z0gxRHBLZHNxR3J0NmhJVzJWVTRHdmpRU2I5bGJIeEFWS0d0ZDc0ZW9YcmRDY2Z5TVQ4TFJ1TWNhSGVTbW1uYmdDRW9YbUVFQnFvRUpZZGYyQVFJb1B5UWlPX2JjZDVUWDVIUk5Wc2xTQThqRU9jWjBSUDBidXAwQUc0dm9acUpCZ3hfYkpjV3RXNXRRODVqVUlsanNQcW0tR01SSXlXcm8tdlJheXZTazVldW93SDJTbTQ0RnNWVzdYSUhKQW5oVlh0WDJ0czNDQlJBVVl3S3F3V3htOU90WUtiQTZCYVNkRjBfM3FEVmFWTmN2TUZrU0ZxWk9ETTRkSF9SUTFSbUtFNHN0VkdvdDRwekU4YmtnaDhJTUZjR3dYNDdZcjJfSGc1bFRUVm9Xb1FicmlTUU1NbTdSMzVreEFBTzVISGJYVm9hRS1xeW9takF2TnZDNVBoTExyNHdpTkpoV3BidjVOS3d2Y01jU2t3M0M4YUIzR1JlbmY2aXdJa0hScU85NzdaZDBvQ2VxOEhnUGhzbFJsUk8tcmsycGh4Zko5by0yYU5lR0pmSnRZMHNrQ1NHRWRTWUZhZ2kwM2NHZFBzQks4ZHFoTDNrQWE4bHNnMG1xaDVqeldBVV9sVklIX0d6dUF4bVI3dU9Id09VdHRwZE9LYjJEU0hKUEZ4ZFlxdDJPU2h2NE9Scjd5V3dTX1ZqT29pNG9MWHlTVEEyeUxJZzc4SzNYVmZTWjlwY29CTEdOWQ==","email":"it.support@kafd.sa"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTQxMGRiMDEwLTcyZjEtNDBmOC04MGMwLTIyZWU5YzEyNDY3YzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBaalpsT0RBME5ESXhORGMwWm1RNFltRTROVEF5T1RVM01qQTNNRFZsWkNKOS5NWTlsejBjeW5mMW5USVluVDZJMkhqRWk0OEdJQ3BsWHhUTHlSNFlWdGFoM1diaDlIZEEwcElDRHhPNEhHY19UTjNHMzFkSXd2YVRUYlN6ZG1OSjBqaV9HWTZtXzlIZ0dvY01pREZaSTFPZnZ1QU01bnFtZDhLaWx5Z0gxRHBLZHNxR3J0NmhJVzJWVTRHdmpRU2I5bGJIeEFWS0d0ZDc0ZW9YcmRDY2Z5TVQ4TFJ1TWNhSGVTbW1uYmdDRW9YbUVFQnFvRUpZZGYyQVFJb1B5UWlPX2JjZDVUWDVIUk5Wc2xTQThqRU9jWjBSUDBidXAwQUc0dm9acUpCZ3hfYkpjV3RXNXRRODVqVUlsanNQcW0tR01SSXlXcm8tdlJheXZTazVldW93SDJTbTQ0RnNWVzdYSUhKQW5oVlh0WDJ0czNDQlJBVVl3S3F3V3htOU90WUtiQTZCYVNkRjBfM3FEVmFWTmN2TUZrU0ZxWk9ETTRkSF9SUTFSbUtFNHN0VkdvdDRwekU4YmtnaDhJTUZjR3dYNDdZcjJfSGc1bFRUVm9Xb1FicmlTUU1NbTdSMzVreEFBTzVISGJYVm9hRS1xeW9takF2TnZDNVBoTExyNHdpTkpoV3BidjVOS3d2Y01jU2t3M0M4YUIzR1JlbmY2aXdJa0hScU85NzdaZDBvQ2VxOEhnUGhzbFJsUk8tcmsycGh4Zko5by0yYU5lR0pmSnRZMHNrQ1NHRWRTWUZhZ2kwM2NHZFBzQks4ZHFoTDNrQWE4bHNnMG1xaDVqeldBVV9sVklIX0d6dUF4bVI3dU9Id09VdHRwZE9LYjJEU0hKUEZ4ZFlxdDJPU2h2NE9Scjd5V3dTX1ZqT29pNG9MWHlTVEEyeUxJZzc4SzNYVmZTWjlwY29CTEdOWQ==","email":"it.support@kafd.sa"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeIF1AP9NYrBXmkNwtg1X27u8o8OpNIBPiGTRHaKIJqynAwc6NQOrGoxWLk/QH5ODt05NmpRtJlqXKUCezRaJkl8Cu8K0trJPVI635NlRZee0DQ3M0TlJefDxS9krO4kEnEJiByVpWq384IlOTzz60kxAJ367CRmy5qj0SV4FTZ/Zhz0DX6IdulnPb994bxu15EiJhlqk0IOvHlm4jwrMZt670V75O/WAgGUYBTRZkgonUVABrgJ77cYAnINOHlza2AqHqYSG/woCCaokVn9cgueZ2eFVv7jFTIDFH1beQ6y7HBxXy1DwpNC5Wcrte4n3oD3Y92EAg9caeo1cv7vjVvWuD8pslPJU6xsFC4GEkLFXhoJ1nxgcLEvCm0BVcAUpdT3kuhJW5Bd4WiObRCYHFO/Qe7O8m3xAnBJOCSDssVc1f2HY7Vfr/GsWogrN/WtHcAPSS9RUGR+vA2t+BEtFdhXnX2zwSDlZKwHrrmhFUvNMH0sM+xMFXarsJdCbNLw8= ocpadmin@bs.mod-pocp-clu02.mod.mil'

